// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantAPI.Data;

#nullable disable

namespace RestaurantAPI.Migrations
{
    [DbContext(typeof(RestaurantOrderDbContext))]
    partial class RestaurantOrderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestaurantAPI.Data.Basket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Basket");
                });

            modelBuilder.Entity("RestaurantAPI.Data.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Salads"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Soups"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Chicken-Dishes"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Beef-Dishes"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Seafood-Dishes"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Vegetable-Dishes"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Bits&Bites"
                        },
                        new
                        {
                            Id = 8,
                            Name = "On-The-Side"
                        });
                });

            modelBuilder.Entity("RestaurantAPI.Data.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Nuts")
                        .HasColumnType("bit");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Spiciness")
                        .HasColumnType("int");

                    b.Property<bool>("Vegeterian")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Image = "https://course-jsbasic.javascript.ru/assets/products/laab_kai_chicken_salad.png",
                            Name = "Laab kai chicken salad",
                            Nuts = true,
                            Price = 10.0,
                            Spiciness = 2,
                            Vegeterian = false
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Image = "https://course-jsbasic.javascript.ru/assets/products/som_tam_papaya_salad.png",
                            Name = "Som tam papaya salad",
                            Nuts = false,
                            Price = 9.5,
                            Spiciness = 0,
                            Vegeterian = true
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Image = "https://course-jsbasic.javascript.ru/assets/products/tom_yam.png",
                            Name = "Tom yam kai",
                            Nuts = false,
                            Price = 7.0,
                            Spiciness = 3,
                            Vegeterian = false
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Image = "https://course-jsbasic.javascript.ru/assets/products/tom_kha.png",
                            Name = "Tom kha kai",
                            Nuts = false,
                            Price = 7.0,
                            Spiciness = 3,
                            Vegeterian = false
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Image = "https://course-jsbasic.javascript.ru/assets/products/tom_kha.png",
                            Name = "Tom kha koong",
                            Nuts = false,
                            Price = 8.0,
                            Spiciness = 2,
                            Vegeterian = false
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Image = "https://course-jsbasic.javascript.ru/assets/products/tom_yam.png",
                            Name = "Tom yam koong",
                            Nuts = false,
                            Price = 8.0,
                            Spiciness = 4,
                            Vegeterian = false
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Image = "https://course-jsbasic.javascript.ru/assets/products/tom_yam.png",
                            Name = "Tom yam vegetarian",
                            Nuts = false,
                            Price = 7.0,
                            Spiciness = 1,
                            Vegeterian = true
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Image = "https://course-jsbasic.javascript.ru/assets/products/tom_kha.png",
                            Name = "Tom kha vegetarian",
                            Nuts = false,
                            Price = 7.0,
                            Spiciness = 1,
                            Vegeterian = true
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Image = "https://course-jsbasic.javascript.ru/assets/products/sweet_n_sour.png",
                            Name = "Sweet 'n sour chicken",
                            Nuts = true,
                            Price = 14.0,
                            Spiciness = 2,
                            Vegeterian = false
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Image = "https://course-jsbasic.javascript.ru/assets/products/chicken_cashew.png",
                            Name = "Chicken cashew",
                            Nuts = true,
                            Price = 14.0,
                            Spiciness = 1,
                            Vegeterian = false
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Image = "https://course-jsbasic.javascript.ru/assets/products/kai_see_ew.png",
                            Name = "Kai see ew",
                            Nuts = false,
                            Price = 14.0,
                            Spiciness = 4,
                            Vegeterian = false
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            Image = "https://course-jsbasic.javascript.ru/assets/products/beef_massaman.png",
                            Name = "Beef massaman",
                            Nuts = false,
                            Price = 14.5,
                            Spiciness = 2,
                            Vegeterian = false
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 5,
                            Image = "https://course-jsbasic.javascript.ru/assets/products/chu_chee.png",
                            Name = "Seafood chu chee",
                            Nuts = false,
                            Price = 16.0,
                            Spiciness = 2,
                            Vegeterian = false
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            Image = "https://course-jsbasic.javascript.ru/assets/products/red_curry.png",
                            Name = "Penang shrimp",
                            Nuts = true,
                            Price = 16.0,
                            Spiciness = 4,
                            Vegeterian = false
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 6,
                            Image = "https://course-jsbasic.javascript.ru/assets/products/green_curry.png",
                            Name = "Green curry veggies",
                            Nuts = true,
                            Price = 12.5,
                            Spiciness = 0,
                            Vegeterian = true
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 6,
                            Image = "https://course-jsbasic.javascript.ru/assets/products/tofu_cashew.png",
                            Name = "Tofu cashew",
                            Nuts = true,
                            Price = 12.5,
                            Spiciness = 0,
                            Vegeterian = true
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 6,
                            Image = "https://course-jsbasic.javascript.ru/assets/products/red_curry_vega.png",
                            Name = "Red curry veggies",
                            Nuts = false,
                            Price = 12.5,
                            Spiciness = 4,
                            Vegeterian = true
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 6,
                            Image = "https://course-jsbasic.javascript.ru/assets/products/krapau_vega.png",
                            Name = "Krapau tofu",
                            Nuts = false,
                            Price = 12.5,
                            Spiciness = 0,
                            Vegeterian = true
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 7,
                            Image = "https://course-jsbasic.javascript.ru/assets/products/kroepoek.png",
                            Name = "Prawn crackers",
                            Nuts = false,
                            Price = 2.5,
                            Spiciness = 1,
                            Vegeterian = false
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 7,
                            Image = "https://course-jsbasic.javascript.ru/assets/products/fish_cakes.png",
                            Name = "Fish cakes",
                            Nuts = false,
                            Price = 6.5,
                            Spiciness = 1,
                            Vegeterian = false
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 7,
                            Image = "https://course-jsbasic.javascript.ru/assets/products/sate.png",
                            Name = "Chicken satay",
                            Nuts = false,
                            Price = 6.5,
                            Spiciness = 1,
                            Vegeterian = false
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 7,
                            Image = "https://course-jsbasic.javascript.ru/assets/products/satesaus.png",
                            Name = "Satay sauce",
                            Nuts = false,
                            Price = 1.5,
                            Spiciness = 2,
                            Vegeterian = false
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 7,
                            Image = "https://course-jsbasic.javascript.ru/assets/products/koong_hom_pha.png",
                            Name = "Shrimp springrolls",
                            Nuts = false,
                            Price = 6.5,
                            Spiciness = 3,
                            Vegeterian = false
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 7,
                            Image = "https://course-jsbasic.javascript.ru/assets/products/mini_vega_springrolls.png",
                            Name = "Mini vegetarian spring rolls",
                            Nuts = false,
                            Price = 6.5,
                            Spiciness = 2,
                            Vegeterian = false
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 7,
                            Image = "https://course-jsbasic.javascript.ru/assets/products/chicken_loempias.png",
                            Name = "Chicken springrolls",
                            Nuts = false,
                            Price = 6.5,
                            Spiciness = 2,
                            Vegeterian = false
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 8,
                            Image = "https://course-jsbasic.javascript.ru/assets/products/fried_rice.png",
                            Name = "Thai fried rice",
                            Nuts = false,
                            Price = 7.5,
                            Spiciness = 2,
                            Vegeterian = false
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 8,
                            Image = "https://course-jsbasic.javascript.ru/assets/products/kroepoek.png",
                            Name = "Fresh prawn crackers",
                            Nuts = false,
                            Price = 2.5,
                            Spiciness = 1,
                            Vegeterian = false
                        });
                });

            modelBuilder.Entity("RestaurantAPI.Data.Basket", b =>
                {
                    b.HasOne("RestaurantAPI.Data.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("RestaurantAPI.Data.Product", b =>
                {
                    b.HasOne("RestaurantAPI.Data.Category", null)
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RestaurantAPI.Data.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
